---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# Feature importance
```{r}
library(magrittr)
library(dplyr)
library(biomaRt)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
diseaseImportance <- local({
  df <- read.csv("../transfer_feature_importance.csv",sep=",") %>% 
  set_colnames(c("loss","feature"))

  globDF <- read.csv("./global_feature_importance.csv",stringsAsFactors = F) %>% 
    set_colnames(c("glob_loss","feature"))
  
  diseaseDF <- read.csv("./ind_disease_transfer_feature_importance.csv",stringsAsFactors = F) %>% 
    set_colnames(c("loss","feature","disease"))
  
  df <- diseaseDF %>% inner_join(globDF,by=c("feature")) %>% 
    mutate(relImp = loss - glob_loss) %>% 
    mutate(type = ifelse(grepl("ENSG.*",feature),"expression",ifelse(grepl("mut",feature),"mutation","clinical"))) %>%
    mutate(feature = ifelse(type=="expression",substr(feature,0,15),feature))
  
  mart       = useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
  allAtts    <- atts <- biomaRt::listAttributes(mart)
  atts       <- c("ensembl_gene_id","hgnc_symbol")
  ensembls   <- df %>% filter(type=="expression") %>% (function(df){df$feature}) %>% unique()
  bmDF       <- getBM(attributes = atts, filters = "ensembl_gene_id", values=ensembls, mart = mart)
  bmDF       <- bmDF %>% set_colnames(c("feature","hgnc"))
  detach("package:biomaRt", unload=TRUE)
  
  library(stringr)
  df2 <- df %>% left_join(bmDF,"feature") %>% mutate(hgnc = ifelse(type=="mutation",str_sub(feature,end=-5),hgnc))
  df2
})

```

# Find oncogene avg importance
```{r}
library(msigdbr)
msigDF  <- msigdbr(species="Homo sapiens", category = "H") 
msigDF2 <- msigDF %>% select(hgnc=human_gene_symbol,gs_name) %>% unique()
df <- diseaseImportance %>% group_by(hgnc) %>% summarize(maxloss=max(glob_loss)) %>% 
  inner_join(msigDF2, by="hgnc") %>% mutate(gs_name = ifelse(is.na(gs_name),"out",gs_name)) %>% 
  filter(nchar(hgnc)>2) 

medloss <- median(df$maxloss)
df2 <- df %>% group_by(gs_name) %>% summarize(tot=n(),imp = sum(maxloss > medloss)) %>% mutate(imp_prev=imp/tot)

ggplot(df,aes(x=reorder(gs_name,loss),y=maxloss)) + geom_boxplot() + coord_flip()
```

## GBM prostate and breast
```{r GBM Prostate and breast}
plotDF <- diseaseImportance %>% 
  filter(disease %in% c("Brain Lower Grade Glioma","Prostate Adenocarcinoma","Breast Invasive Carcinoma")) %>%
  mutate(feature = ifelse(type!="clinical",hgnc,feature)) %>% filter(!grepl("disease_code*",feature)) 

globDF  <- plotDF %>% select(feature,loss=glob_loss,type,hgnc) %>% distinct() %>% 
  group_by(type) %>% arrange(loss)  %>% top_n(6,wt =loss) %>% arrange(type,-loss)

brainDF <- plotDF %>% filter(disease == "Brain Lower Grade Glioma") %>% 
  select(feature,type,glob_loss,loss,diff_imp = relImp) %>% filter(glob_loss>0,diff_imp > 0) %>% 
  group_by(type) %>% top_n(6,wt = loss) %>% arrange(type,-loss)

prostDF <- plotDF %>% filter(disease == "Prostate Adenocarcinoma") %>% 
  select(feature,type,glob_loss,loss,diff_imp = relImp) %>% filter(glob_loss>0,diff_imp > 0) %>% 
  group_by(type) %>% top_n(6,wt=loss) %>% arrange(type,-loss)


breastDF <- plotDF %>% filter(disease == "Breast Invasive Carcinoma") %>% 
  select(feature,type,glob_loss,loss,diff_imp = relImp) %>% filter(glob_loss>0,diff_imp > 0) %>% arrange(-loss) %>% 
  group_by(type) %>% top_n(6) %>% arrange(type,-loss)
```

### gene publication
```{r}
brainDF <- plotDF %>% filter(disease == "Brain Lower Grade Glioma") %>% filter(type=="mutation") %>% 
  dplyr::select(hgnc,glob_loss,loss,diff_imp = relImp) %>% 
  filter(glob_loss>0) %>%
  filter(!is.na(hgnc),nchar(hgnc) > 0) %>% 
  group_by(hgnc) %>% summarize(loss=max(loss)) %>% arrange(-loss) %>% (function(df){
    df %>% mutate(percentile = 1 - row_number()/nrow(df))
  }) 

brainPub <- read.csv("../genes_pubmedcounts_glioma.csv",header=T,stringsAsFactors = F) %>%
  set_colnames(c("row","ensembl","count","hgnc")) %>% dplyr::select(hgnc,pubcount=count) 

brainJoin <- brainPub %>% 
  inner_join(prostDF,by="hgnc") %>% mutate(pubcount = ifelse(is.na(pubcount),0,pubcount)) %>% 
  mutate(hiPub = pubcount > 50, hiLoss = percentile > 0.75)

tbl = table(prostJoin$hiPub,prostJoin$hiLoss)
tbl
chisq.test(tbl)
# p(high percentile | high publication) vs p (high percentile | low publication) = 16 / 66 vs 90 / 464
```

```{r}
prostDF <- plotDF %>% filter(disease == "Prostate Adenocarcinoma") %>% filter(type=="mutation") %>% 
  dplyr::select(hgnc,glob_loss,loss,diff_imp = relImp) %>% 
  filter(glob_loss>0) %>%
  filter(!is.na(hgnc),nchar(hgnc) > 0) %>% 
  group_by(hgnc) %>% summarize(loss=max(loss)) %>% arrange(-loss) %>% (function(df){
    df %>% mutate(percentile = 1 - row_number()/nrow(df))
  }) 

prostPub <- read.csv("../genes_pubmedcounts_prostate.csv",header=T,stringsAsFactors = F) %>%
  set_colnames(c("row","ensembl","count","hgnc")) %>% dplyr::select(hgnc,pubcount=count) 

prostJoin <- prostPub %>% 
  inner_join(prostDF,by="hgnc") %>% mutate(pubcount = ifelse(is.na(pubcount),0,pubcount)) %>% 
  mutate(hiPub = pubcount > 50, hiLoss = percentile > 0.75)

tbl = table(prostJoin$hiPub,prostJoin$hiLoss)
tbl
chisq.test(tbl)
# p(high percentile | high publication) vs p (high percentile | low publication) 6 / 11 vs 9 / 68
```

# Drug importance

## Global
```{r}
relDF <- read.csv("./relationships/relationships.tsv",sep="\t",stringsAsFactors = F) %>% 
  filter(Entity1_type=="Gene",Entity2_type=="Chemical",Association=="associated") %>% 
  set_colnames(c("id1","hgnc","type1","id2","chemName","type2","evidence","association","PK","PD","PMIDs"))

globDF <- diseaseImportance %>% select(loss=glob_loss,hgnc,type) %>% distinct()

drugDF <- globDF %>% inner_join(relDF,by="hgnc") %>% filter(nchar(PMIDs)>5)  %>% 
  select(chemName,hgnc,loss) %>% distinct() %>% group_by(chemName) %>% 
  top_n(3,wt=loss) %>% summarize(sumImportance=sum(loss),genes = paste(hgnc,collapse=","))
```

## Disease specific
```{r}
brainDrug <- diseaseImportance %>% filter(disease=="Brain Lower Grade Glioma") %>% 
  inner_join(relDF,by="hgnc") %>% group_by(chemName) %>% 
  top_n(3,wt=loss) %>% summarize(sumImportance=sum(loss),genes = paste(hgnc,collapse=","))

prostateDrug <- diseaseImportance %>% filter(disease=="Prostate Adenocarcinoma") %>% 
  inner_join(relDF,by="hgnc") %>% group_by(chemName) %>% 
  top_n(3,wt=loss) %>% summarize(sumImportance=sum(loss),genes = paste(hgnc,collapse=","))
```









